CATALOGUE_HOST: catalogue-backend.{{ env }}.mydaws.site
USER_HOST: user-backend.{{ env }}.mydaws.site
CART_HOST: cart-backend.{{ env }}.mydaws.site
SHIPPING_HOST: shipping-backend.{{ env }}.mydaws.site
PAYMENT_HOST: payment-backend.{{ env }}.mydaws.site